name: License Check
on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      server: ${{ steps.server.outputs.any_modified }}
      worker: ${{ steps.worker.outputs.any_modified }}
      web: ${{ steps.web.outputs.any_modified }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Server changes
        id: server
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
        with:
          files: |
            server/go.mod
            server/go.sum
      - name: Worker changes
        id: worker
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
        with:
          files: |
            worker/go.mod
            worker/go.sum
      - name: Web changes
        id: web
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
        with:
          files: |
            web/package.json
            web/yarn.lock

  server-license-check:
    name: Server License Check
    needs: prepare
    if: needs.prepare.outputs.server == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod
          check-latest: true
          cache-dependency-path: |
            server/go.sum
      - uses: reearth/actions/license-checker/go@b63f7da8796f4514712947e1a4902994be29e3d9
        with:
          subdirectory: server
  worker-license-check:
    name: Worker License Check
    needs: prepare
    if: needs.prepare.outputs.worker == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: worker/go.mod
          check-latest: true
          cache-dependency-path: |
            worker/go.sum
      - uses: reearth/actions/license-checker/go@b63f7da8796f4514712947e1a4902994be29e3d9
        with:
          subdirectory: worker
  web-license-check:
    name: Web License Check
    needs: prepare
    if: needs.prepare.outputs.web == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install
      - uses: reearth/actions/license-checker/npm@b63f7da8796f4514712947e1a4902994be29e3d9
        with:
          subdirectory: web
